### ISSUE TITLE
SCRIPT ERROR: Invalid Lua type in __data

### ISSUE THREAD

**Issue by ImreHungary** [wobozkyng/esx_realweapons#1]
[  script:es_extended] SCRIPT ERROR: Invalid Lua type in __data
[  script:es_extended] > CreateObject (CreateObject.lua:12)
[  script:es_extended] > fn (@es_extended/server/onesync.lua:91)
-------------------------------------------------------------------
ESX 1.8.5
ox_inventory (2.21.0)

**Comment by wobozkyng** [comment]
Hi, did you modify the resource (esx_realweapons) ?

**Comment by ImreHungary** [comment]
Hi, no I doesn't .

**Comment by wobozkyng** [comment]
In your es_extended/server/onesync.lua:91, on CreateObject function, replace argument "coords" with "vector".
So that would be like 
`local entity = CreateObject(model, vector, true, true)`

**Comment by ImreHungary** [comment]
thx for the help its working now.
